export default {
  translation: {
    TITLE: 'AI Selection',
    RETURN: 'Choose Again',
    RESULT: 'Result',
    SELECTION: 'Enter what you would like AI to choose for you',
    CHOICES: 'Choices',
    ROW_REMOVE: 'Remove',
    SELECTION_TYPE: 'What to choose',
    SELECTION_BIAS: 'Conditions',
    OPTIONAL: '(optional):',
    REQUIRED: '(required):',
    TYPE_PLACEHOLDER: 'Ex: Organizer, Travel Destination, Gift',
    BIAS_PLACEHOLDER: 'Ex: Budget is within $50, Rainy weather',
    ADD_OPTION: 'Add Choice',
    SELECT_BUTTON: 'Select',
    SELECTING: 'Selecting...',
    RESULT_TITLE: 'Selection Result',
    COPY_BUTTON: 'Copy Result',
    REASON: 'Reason',
    THEME: 'Theme',
    INSTRUCTION_TITLE: 'Instruction',
    INSTRUCTION_DESCRIPTION1: '"Selection Result": "{Selected Choice}",',
    INSTRUCTION_DESCRIPTION2: '"Reason": "{Selected Reason}"',
    OUTPUT_FORMAT_TITLE: 'Output Format',
    OUTPUT_FORMAT_DESCRIPTION1: 'Output the most suitable choice',
    OUTPUT_FORMAT_DESCRIPTION2: 'Select the most suitable choice based on your bias and judgment',
  },
};
