export default {
  translation: {
    TITLE: '選択アプリ',
    RETURN: 'もう一度選ぶ',
    RESULT: '結果',
    SELECTION: 'AIに選んでもらいたいものを入力してください',
    CHOICES: '選択肢',
    ROW_REMOVE: 'を削除',
    SELECTION_TYPE: '何を選ぶか',
    SELECTION_BIAS: '前提条件',
    OPTIONAL: '（任意）：',
    REQUIRED: '（必須）：',
    TYPE_PLACEHOLDER: '例：幹事、旅行先、プレゼント',
    BIAS_PLACEHOLDER: '例：予算は5千円以内、雨天',
    ADD_OPTION: '選択肢を追加',
    SELECT_BUTTON: '選択する',
    SELECTING: '選択中...',
    RESULT_TITLE: '選択結果',
    COPY_BUTTON: '結果をコピー',
    REASON: '理由',
    THEME: 'テーマ',
    INSTRUCTION_TITLE: '指示',
    INSTRUCTION_DESCRIPTION1: '"選択結果": "{選んだ選択肢}",',
    INSTRUCTION_DESCRIPTION2: '"理由": "{選んだ理由}"',
    OUTPUT_FORMAT_TITLE: '出力形式',
    OUTPUT_FORMAT_DESCRIPTION1: '最もふさわしいを選択肢選んでください',
    OUTPUT_FORMAT_DESCRIPTION2: 'あなたの偏見と独断で選択して、その理由も述べてください',
  },
};
